openapi: 3.1.0
info:
  title: NicoGPT Backend API
  version: "1.0"
servers:
  - url: https://api.bettergetnico.com
paths:
  /ping:
    get:
      operationId: ping
      summary: Health check for the backend
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
