openapi: 3.1.0
info:
  title: NicoGPT Backend API
  version: "1.0"
servers:
  - url: https://api.bettergetnico.com
paths:
  /ping:
    get:
      operationId: ping
      summary: Health check for the backend
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
  /fetch-doc:
    get:
      operationId: fetchGoogleDoc
      summary: Fetch plain text content from a public Google Doc
      parameters:
        - name: docUrl
          in: query
          required: true
          description: Public URL of the Google Doc
          schema:
            type: string
      responses:
        '200':
          description: Content fetched from the document
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  content:
                    type: string
